language: node_js

node_js: 10

jobs:
  include:
  - stage: test
    script:
    - npm link
    - npm run lint
    - h1 config cli
    - npm run docs
    - git status
    - git diff HEAD
    - test -z "$(git status --porcelain docs)"
    - scripts/markown_lint.sh
    - npm run build
    - dist/h1-linux --help
    - dist/rbx-linux --help
  - stage: build & deploy
    sudo: required
    services:
    - docker
    script:
    - cd ./monitoring
    - ./deploy_image.sh
    branches:
      only:
      - develop

env:
  global:
  - secure: OWv994Utmdlykxiu4tfzyTdVd4diUbKrJ5H4oo6+R0QgSAisZZNgAdnKLjwVvZuEMBNYYBIggQVYJdBzmaQV/FYvV+hqkyCkCfBef/kVOmyY+7xFT0rOV74wHFCev34/hxWyDjmyrmBz4UvVNWty3oQZGxw0LxBSbXFYHpEfvW0ysX/P6e4hkzMpnqGEpSTxGqIjCdMVTKrdoCTWwM5m56Q7GVgO3X7HwWVBZR1zdwzbb0zKKyDc4oG2cz7FuHUMeYtKW3kxAzh3Jvi18kNNEpCdUE2tGD1Gx4VO6sqklsnnlNrUkAnLOTLxwfDPL0MJyWwK1wxtsYis6NwlOqcNh7QnyUF1So/HXj5oybjWZ926YvybLVEXgoV7wKKprVut6ruZW/ihSD7DIy5NitRSemye8NJNtcsF/6ZDSpULWuTO+WvMqpCQh3HZr/Xm5eUQbRiwhCNf+qVh1adt15rimQA8g22ZLVgu1FxHAPeyHl3f95srTqHShWySsUyKv64gdH7zoNk+Q5OrGykO6/ioDnjf4MQnsQPL/jCRt4w8LXs9OA6i3rLCaYE+Q/93BIPP/BrZ3etfC4q5Ioq4m4h5s3ihYHJzBbO0cZK4dugo4lLnIRVSbD54DM4Nw4i6d1FL5mom2jwPbwReFs/1OHgNlOWcS/6AEUxFaESoIly3K6E=
  - secure: xe7OEBOUXCVySdxqWHeqDmegQSXhdgkvWg1wN0wMd1kdg6wQuHT5hhuu/e3BpwNWSUSav1wEYBjDzkjlOlKGZV5MbQdZdj4p+WOeRQRwKEaLTaoPc7qx9pSTH+GCBaqtJLdyP3qw0Ed9HUWgu+AmcnjBTBrefhR0R0hDdPoyoeA2LMfplJDaSRumPNfmjrOrQRkPL/LpoclV+B4c5HHIE4pysARa0aqWL4LBYbv4PsWsGKeGAixiY7mjMsf2l6gosU1zlcnulawY+FNtBiWXG3EqcW+iyOy3A8Pe2WpXF7DZwYDrn1Tmbv74WyENivFNnN2AEJsZIVSC8oB7fv/gip0qr9Z/krWZd+26Kj6iS8f2xc3cEly0SA819VphPUW/EIipDNJ8/7xDZoVrDAb8bvQZYTDE5tnaqfiq3FbWk1hNV9g+cetv/vAx+l7ZEPsJp55DCc2nrbYwL7gcEUX3cMXxXYr0T1JLSbuLNWlFGb5//2uX3lqX7x0ZtkgGhMeww9U+GUaM5rJHHkLzPUSiWezboLeRABLR2Koh116HgQyBb3G55MnB1ZUwjMBnyDZRJDIa1yRut2iKwNJrKzfDvPi5YsGLUDVEeTcMwiPzuIeihZjGUZZB9JD/iGoxlYZxP7yW+uN3tl5D8CumpxG24fJpN8rD7/KYWp1dfjzlUlk=
  - secure: S58PLGkAtRwH+8TjtTTeg10NPpPZWpMNRHaOPA+ifEuioJw3hi+KG6WIDGHFGnzTjlL35aHYsz2+YZqJ+RWUs3UFjh2oMRixZu041S0kglG2eBQvA568x7pVIwXjIZWT6ItlgCYVHe9JCyyNGQbcF29/AsdJ+mt4ggLK4Tkj8Z03qgpdN3SMApQl2Qt+yY2N+CHAQhFBx1ogovYF2otU99OgnKEvFEpiN409I/DJc6b03G78cxQTMO6Hy2gwy/Q9B2YGchvCpYTsldGPXr7g3l1Lfqx5K5IrQ3tOJtC0YocMlK2uhxuJ4Xp1tarFo1m4YquHBnNk9ADYnBG45IZVB6dYNAo0jQiAbVHFhD0KLbT6ymbHKboI/rLtep+cH6ot/BKG50MI2TbRJf4K5ct2UXKahUi9Glr9E5t5GtJHsS+HxXifMRsIu1+hle1Em1GV6TskLTqDLdGkVqa+iBzPIz6BFg6GsLIlVtM2kwnpljgF4sWylWW00wsaL0v2KG5bP7Lz37HunLKyKpECKxgAJWZgoD4xgXB5YG4NMqYoqUSNqYaYy2z3H6Mp/Chuj9HTMVh0H0Y8C2b38DRWjLyS93Syy9PO/R+ZIJZcJvHLI0HBicRvF/EKUjV3p2S3E6dJ8rKsRUvHMlsr91KMZqjEx9ZLG7DZ/9kc9yK+CbHrY7U=
