language: node_js

node_js: 10

jobs:
  include:
  - stage: test
    script:
    - npm link
    - npm run lint
    - h1 config cli
    - npm run docs
    - git status
    - git diff HEAD
    - test -z "$(git status --porcelain docs)"
    - scripts/markown_lint.sh
    - npm run build
    - dist/h1-linux --help
    - dist/rbx-linux --help
  - stage: build & deploy
    sudo: required
    services:
    - docker
    script:
    - cd ./monitoring
    - ./deploy_image.sh