language: node_js

node_js: '12'
dist: xenial

services:
  - docker

jobs:
  include:
  - stage: test
    script:
    - npm ci
    - npm link
    - npm run lint
    - npm run docs
    - git status
    - git diff HEAD
    - test -z "$(git status --porcelain docs)"
    - scripts/markown_lint.sh
    - npm publish --dry-run
    - npm run-script build
    - tar -xzvf ./dist/h1-linux.tar.gz
    - ./scripts/test_version_output.sh ./h1
    - rm ./h1
    - tar -xzvf ./dist/h1-alpine.tar.gz
    - ./scripts/test_version_output.sh ./h1 alpine
    - rm ./h1
  - stage: build & deploy
    sudo: required
    script:
    - >
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        TAG_NAME="${TRAVIS_BRANCH}";

        if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
            TAG_NAME="latest";
        fi;

        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin "${DOCKER_REGISTRY}";
        docker build -t "${DOCKER_REGISTRY}/cli:${TAG_NAME}" .;
        docker run --rm "${DOCKER_REGISTRY}/cli:${TAG_NAME}" h1 --help;
        docker push "${DOCKER_REGISTRY}/cli:${TAG_NAME}";
        if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
          cd ./monitoring;
          ./deploy_image.sh;
        fi;
      fi;
