language: node_js

node_js: 10

services:
  - docker

jobs:
  include:
  - stage: test
    script:
    - npm link
    - npm run lint
    - h1 config cli
    - npm run docs
    - git status
    - git diff HEAD
    - test -z "$(git status --porcelain docs)"
    - scripts/markown_lint.sh
    - npm run build
    - dist/h1-linux --help
    - docker run --rm -v $(pwd)/dist/h1-alpine:/usr/local/bin/h1 alpine ash -c 'apk add libstdc++ && h1 --help'
    - dist/rbx-linux --help
    - docker run --rm -v $(pwd)/dist/rbx-alpine:/usr/local/bin/rbx alpine ash -c 'apk add libstdc++ && rbx --help'
  - stage: build & deploy
    sudo: required
    script:
    - >
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        export TAG_NAME="${TRAVIS_BRANCH}";

        if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
            export TAG_NAME="latest";
        fi;

        cd ./monitoring;
        ./deploy_image.sh
      fi;
